# Generated by Django 4.2.5 on 2023-09-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soft_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
    ]
